FROM node:20

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY . .

EXPOSE 3001


VOLUME [ "/usr/src/app" ]

CMD [ "npm", "run", "dev" ]