version: '3.8'
services:
  duckdns:
    image: ghcr.io/linuxserver/duckdns:arm32v7-latest
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SUBDOMAINS=cimtel-adatar
      - TOKEN=d0aa4928-aca4-4496-95d6-d3f3012d5a58
    restart: unless-stopped
