# Puerto en el que se ejecuta la aplicación
[build]
bin = "main"
cmd = "go build -o main ."
dir = "."
exclude_dir = ["node_modules", "public"]

[run]
args = []
env = []
log_prefix = "air"
port = "8080"
