
FROM golang:alpine3.18
# Copia los archivos necesarios para la aplicación
RUN mkdir -p /go/src/app
WORKDIR /go/src/app
COPY . .



RUN go mod tidy
RUN go build .


VOLUME [ "/go/src/app" ]

EXPOSE 8000

CMD ["api_rest_go.exe"]
