
FROM golang:latest
# Copia los archivos necesarios para la aplicación
RUN mkdir -p /go/src/app
WORKDIR /go/src/app
COPY . .


RUN go install github.com/cosmtrek/air@latest
RUN go get github.com/gorilla/mux
RUN go get github.com/lib/pq
RUN go get github.com/joho/godotenv


VOLUME [ "/go/src/app" ]

EXPOSE 8000

CMD ["air"]