
FROM golang:1.20-alpine
# Copia los archivos necesarios para la aplicación
WORKDIR /app
COPY . .


RUN go install github.com/cosmtrek/air@latest
RUN go get github.com/gorilla/mux
RUN go get github.com/lib/pq

EXPOSE 8000

CMD ["air"]