-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Docentes"
(
    id integer NOT NULL DEFAULT nextval('docentes_id_seq'::regclass),
    "Cog_Docente" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Nom_Docente" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Docentes_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Estudiantes"
(
    id integer NOT NULL DEFAULT nextval('estudiantes_id_seq'::regclass),
    "TipoDoc" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    people_code_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Identificacion" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Nombres" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "EstadoAlumnoPrograma" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Semestre" character varying(255) COLLATE pg_catalog."default",
    "Direccion" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Ciudad" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Departamento" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "TelFijo" character varying(255) COLLATE pg_catalog."default",
    "TelMovil" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Genero" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "SemeNumero" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "PensumId" integer NOT NULL,
    CONSTRAINT "Estudiantes_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Facultades"
(
    id integer NOT NULL DEFAULT nextval('facultades_id_seq'::regclass),
    "NombreFacultad" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Facultades_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."MateriaPorPensums"
(
    id integer NOT NULL DEFAULT nextval('materiaporpensums_id_seq'::regclass),
    "Seme" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "SemMateriaNum" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "PensumId" integer NOT NULL,
    "MateriaId" integer NOT NULL,
    CONSTRAINT "MateriaPorPensums_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Materias"
(
    id integer NOT NULL DEFAULT nextval('materias_id_seq'::regclass),
    "CodigoMateria" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "NombreMateria" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "TipoMateria" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Materias_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Notas"
(
    id integer NOT NULL DEFAULT nextval('notas_id_seq'::regclass),
    "GRADE_ACTIVITY" character varying(255) COLLATE pg_catalog."default",
    "FINAL_GRADE" character varying(255) COLLATE pg_catalog."default",
    "Nota" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Gano" integer NOT NULL,
    "Perdio" integer NOT NULL,
    "Rango" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "ProxNotaMin" character varying(255) COLLATE pg_catalog."default",
    "Seccion" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "EstudianteId" integer NOT NULL,
    "MateriaId" integer NOT NULL,
    "ProgramaId" integer NOT NULL,
    "DocenteId" integer NOT NULL,
    "PeriodoAcademicoId" integer NOT NULL,
    CONSTRAINT "Notas_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Pensums"
(
    id integer NOT NULL DEFAULT nextval('pensums_id_seq'::regclass),
    "Pensum" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Semestres" character varying(255) COLLATE pg_catalog."default",
    "ProgramaId" integer NOT NULL,
    CONSTRAINT "Pensums_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."PeriodoAcademicos"
(
    id integer NOT NULL DEFAULT nextval('periodoacademicos_id_seq'::regclass),
    "Year" integer NOT NULL,
    "Periodo" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "NomNotaPeriodo" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PeriodoAcademicos_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Programas"
(
    id integer NOT NULL DEFAULT nextval('programas_id_seq'::regclass),
    "NombrePrograma" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Sede" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Sesion" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "FacultadeId" integer NOT NULL,
    CONSTRAINT "Programas_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Rols"
(
    id integer NOT NULL DEFAULT nextval('rols_id_seq'::regclass),
    rol character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Rols_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Users"
(
    id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    "Avatar" character varying(255) COLLATE pg_catalog."default",
    "Nombre" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Password" character varying(255) COLLATE pg_catalog."default",
    "RolId" integer NOT NULL,
    "Datos" character varying(255)[] COLLATE pg_catalog."default",
    CONSTRAINT "Users_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Estudiantes"
    ADD CONSTRAINT "Estudiantes_PensumId_fkey" FOREIGN KEY ("PensumId")
    REFERENCES public."Pensums" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."MateriaPorPensums"
    ADD CONSTRAINT "MateriaPorPensums_MateriaId_fkey" FOREIGN KEY ("MateriaId")
    REFERENCES public."Materias" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."MateriaPorPensums"
    ADD CONSTRAINT "MateriaPorPensums_PensumId_fkey" FOREIGN KEY ("PensumId")
    REFERENCES public."Pensums" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Notas"
    ADD CONSTRAINT "Notas_DocenteId_fkey" FOREIGN KEY ("DocenteId")
    REFERENCES public."Docentes" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Notas"
    ADD CONSTRAINT "Notas_EstudianteId_fkey" FOREIGN KEY ("EstudianteId")
    REFERENCES public."Estudiantes" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Notas"
    ADD CONSTRAINT "Notas_MateriaId_fkey" FOREIGN KEY ("MateriaId")
    REFERENCES public."Materias" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Notas"
    ADD CONSTRAINT "Notas_PeriodoAcademicoId_fkey" FOREIGN KEY ("PeriodoAcademicoId")
    REFERENCES public."PeriodoAcademicos" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Notas"
    ADD CONSTRAINT "Notas_ProgramaId_fkey" FOREIGN KEY ("ProgramaId")
    REFERENCES public."Programas" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Pensums"
    ADD CONSTRAINT "Pensums_ProgramaId_fkey" FOREIGN KEY ("ProgramaId")
    REFERENCES public."Programas" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Programas"
    ADD CONSTRAINT "Programas_FacultadeId_fkey" FOREIGN KEY ("FacultadeId")
    REFERENCES public."Facultades" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Users"
    ADD CONSTRAINT "Users_RolId_fkey" FOREIGN KEY ("RolId")
    REFERENCES public."Rols" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

END;