version: "3.9"
services:
  adatar:
    container_name: api_adatar
    restart: always
    build: .
    ports:
      - 3004:3001
    #environment:
      #- PORT=3001
      #- DB_USER=admin
      #- DB_PASSWORD=12345
      #- DB_HOST=localhost
      #- DB=adatar
    volumes:
      - .:/usr/src/api


  service:
    container_name: go-api_adatar
    restart: always
    build: ./service
    ports:
      - 8000:8000
   # environment:
      #- DB_USER=admin
     # - DB_PASSWORD=12345
      #- DB_HOST=localhost:8080
     # - DB=adatar
    volumes:
      - ./service:/go/src/app
 

  

# docker run -p 80:80 --name PgAdmin -e PGADMIN_DEFAULT_EMAIL=admin@gmail.com -e PGADMIN_DEFAULT_PASSWORD=admin -d dpage/pgadmin4
# docker run -p 5432:5432 --name database -e POSTGRES_USER=admin -e POSTGRES_PASSWORD=12345 -e POSTGRES_DB=adatar -d postgres
# docker inspect database
# docker run -p 3004:3001 --name api -e DB_USER=admin -e DB_PASSWORD=12345 -e DB_HOST=172.17.0.1 -e DB=adatar -d <NAME IMAGEN>
# docker run -p 3000:3000 --name next-app -d 
