version: "3.9" 
services: 
  api:
    container_name: api_adatar
    restart: always
    build: .
    ports:
      - 8000:3001
    links:
      - postgres
    volumes:
      - .:/usr/src/app

  postgres: 
    image: postgres
    restart: always 
    ports: 
      - 5432:5432
    environment: 
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: adatar  
  pgadmin: 
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: 
      - 80:80
    depends_on:
      - postgres 
    logging: 
      driver: none
       

# docker run -p 80:80  -e PGADMIN_DEFAULT_EMAIL=admin@gmail.com -e PGADMIN_DEFAULT_PASSWORD=admin -d dpage/pgadmin4
# docker run -p 5432:5432 --name postgres -e DATABASE_HOST=127.0.0.1 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=adatar -d postgres
# docker inspect postgres
# docker run -p 3000:3001  -e DB_USER=postgres -e DB_PASSWORD=postgres -e DB_HOST=172.17.0.2 -e DB=adatar -d <NAME IMAGEN>